/opt/conda/envs/face/lib/python3.6/site-packages/torchvision/datasets/mnist.py:45: UserWarning: train_labels has been renamed targets
  warnings.warn("train_labels has been renamed targets")
/opt/conda/envs/face/lib/python3.6/site-packages/torch/nn/functional.py:1351: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
Train epoch 0.0 	 Loss 543.577265625
Train epoch 1.0 	 Loss 176.3348046875
Train epoch 2.0 	 Loss 152.997158203125
Train epoch 3.0 	 Loss 143.172080078125
Train epoch 4.0 	 Loss 147.087705078125
Train epoch 5.0 	 Loss 145.19751953125
Average Loss:  159.66571617838542
Test Loss:  tensor(14016.0020, device='cuda:0')
Traceback (most recent call last):
  File "cvae.py", line 126, in <module>
    sample = cvae.decoder(z, c).to(device)
  File "cvae.py", line 52, in decoder
    h = F.relu(self.fc4(concat_input))
  File "/opt/conda/envs/face/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/envs/face/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/opt/conda/envs/face/lib/python3.6/site-packages/torch/nn/functional.py", line 1370, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: size mismatch, m1: [100 x 102], m2: [12 x 512] at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/THC/generic/THCTensorMathBlas.cu:290
